services:
  - type: web
    name: rguvsj-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false # Ovo će vam omogućiti da postavite vrednost kroz Render dashboard 